export enum ComponentStatusTypes {
  ISSUE = 'ISSUE',
  NONE = 'NONE',
  SUCCESS_COMPONENT = 'SUCCESS.COMPONENT',
  INFO_COMPONENT = 'INFO.COMPONENT',
  ERROR_COMPONENT = 'ERROR.COMPONENT',
  WARNING_COMPONENT = 'WARNING.COMPONENT',
}
