export enum StatusTypes {
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  INFO = 'INFO',
  ISSUE = 'ISSUE',
  NONE = 'NONE',
  ERROR_COMPONENT = 'ERROR.COMPONENT',
  WARNING_COMPONENT = 'WARNING.COMPONENT',
}
